import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased bg-zinc-200`}>
        <div className="mx-auto min-h-screen max-w-3xl xl:max-w-5xl xl:px-0 px-4 bg-white">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
